export default {
	transparency: "static/images/transparency.png",
	flowers2: "static/images/flowers2.jpg",
	flowers: "static/images/flowers.jpg",
	spotifyWave: "static/images/spotify-wave.png",
	posters: {
		brushBackground: "static/images/posters/brush.png",
		backgroundPattern: "static/images/posters/background-pattern.png",
		calendar: "static/images/posters/calendar.png",
		clippedImage: "static/images/posters/crop.webp",
		clock: "static/images/posters/clock.png",
		cloud: "static/images/posters/cloud.png",
		cylinder: "static/images/posters/cylinder.png",
		contour: "static/images/posters/contour.png",
		framedImage: "static/images/posters/frame.png",
		polaroidCard: "static/images/posters/polaroid.webp",
		poppyFlower: "static/images/posters/poppyFlower.png",
		spiral: "static/images/posters/spiral.png",
		spotifyCard: "static/images/posters/spotify.png",
		spring: "static/images/posters/spring.png",
		stickerBadge: "static/images/posters/sticker-badge.png",
		weatherWidget: "static/images/posters/weather.png",
		waves: "static/images/posters/waves.png",
	},
	presets: {
		calendar: "static/images/presets/calendar.jpg",
		clippedImage: "static/images/presets/tornPaper.png",
		clock: "static/images/presets/clock.jpg",
		cylinder: "static/images/presets/cylinder.jpg",
		polaroid: "static/images/presets/polaroid.jpg",
		frame: "static/images/presets/frame.jpg",
		spotify: "static/images/presets/spotify.jpg",
	},
};
