export default {
	templatePictures: [
		"static/images/template-pictures/1.jpg",
		"static/images/template-pictures/2.jpg",
		"static/images/template-pictures/3.jpg",
		"static/images/template-pictures/4.jpg",
		"static/images/template-pictures/5.jpg",
		"static/images/template-pictures/6.jpg",
		"static/images/template-pictures/7.jpg",
		"static/images/template-pictures/8.jpg",
	],
	transparency: "static/images/transparency.png",

	flowers2: "static/images/flowers2.jpg",
	flowers: "static/images/flowers.jpg",
	spotifyWave: "static/images/spotify-wave.png",

	mapDark: "static/images/posters/mapDark.jpg",
	mapGreen: "static/images/posters/mapGreen.jpg",
	mapRegular: "static/images/posters/mapRegular.jpg",
	mapRegular,
	posters: {
		arrows: "static/images/posters/arrows.png",
		brushBackground: "static/images/posters/brush.png",
		backgroundPattern: "static/images/posters/background-pattern.png",
		calendar: "static/images/posters/calendar.png",
		charts: "static/images/posters/charts.png",
		clippedImage: "static/images/posters/crop.webp",
		clock: "static/images/posters/clock.png",
		cloud: "static/images/posters/cloud.png",
		color: "static/images/posters/color.png",
		pill: "static/images/posters/cylinder.png",
		contour: "static/images/posters/contour.png",
		"Deco Shapes": "static/images/posters/shapes.png",
		frame: "static/images/posters/frame.png",
		flowerHeads: "static/images/posters/flowerHeads.png",
		grid: "static/images/posters/grid.png",
		layouts: "static/images/posters/layouts.png",
		map: "static/images/posters/map.png",
		polaroid: "static/images/posters/polaroid.webp",
		poppyFlower: "static/images/posters/poppyFlower.png",
		spiral: "static/images/posters/spiral.png",
		spotifyCard: "static/images/posters/spotify.png",
		ribbon: "static/images/posters/ribbon.png",
		stickerBadge: "static/images/posters/sticker-badge.png",
		weather: "static/images/posters/weather.png",
		waves: "static/images/posters/waves.png",
	},
	presets: {
		calendar: "static/images/presets/calendar.jpg",
		clippedImage: "static/images/presets/tornPaper.png",
		clock: "static/images/presets/clock.jpg",
		cylinder: "static/images/presets/cylinder.jpg",
		polaroid: "static/images/presets/polaroid.jpg",
		frame: "static/images/presets/frame.jpg",
		map: "static/images/presets/map.jpg",
		spotify: "static/images/presets/spotify.jpg",
	},
};
