export default {
	templatePictures: [
		"static/images/template-pictures/1.jpg",
		"static/images/template-pictures/2.jpg",
		"static/images/template-pictures/3.jpg",
		"static/images/template-pictures/4.jpg",
		"static/images/template-pictures/5.jpg",
		"static/images/template-pictures/6.jpg",
		"static/images/template-pictures/7.jpg",
		"static/images/template-pictures/8.jpg",
	],
	transparency: "static/images/transparency.png",

	flowers2: "static/images/flowers2.jpg",
	flowers: "static/images/flowers.jpg",
	spotifyWave: "static/images/spotify-wave.png",

	maps: {
		regular: {
			blob: "static/images/maps/blob-regular.webp",
			folded: "static/images/maps/folded-regular.webp",
			regular: "static/images/maps/regular.webp",
		},
		green: {
			blob: "static/images/maps/blob-green.webp",
			folded: "static/images/maps/folded-green.webp",
			regular: "static/images/maps/green.webp",
		},
		dark: {
			blob: "static/images/maps/blob-dark.webp",
			folded: "static/images/maps/folded-dark.webp",
			regular: "static/images/maps/dark.webp",
		},
		withMarker: {
			regular: {
				blob: "static/images/maps/with-marker/blob-regular.webp",
				folded: "static/images/maps/with-marker/folded-regular.webp",
				regular: "static/images/maps/with-marker/regular.webp",
			},
			green: {
				blob: "static/images/maps/with-marker/blob-green.webp",
				folded: "static/images/maps/with-marker/folded-green.webp",
				regular: "static/images/maps/with-marker/green.webp",
			},
			dark: {
				blob: "static/images/maps/with-marker/blob-dark.webp",
				folded: "static/images/maps/with-marker/folded-dark.webp",
				regular: "static/images/maps/with-marker/dark.webp",
			},
		},
	},

	posters: {
		arrows: "static/images/posters/arrows.webp",
		brushBackground: "static/images/posters/brush.webp",
		backgroundPattern: "static/images/posters/background-pattern.webp",
		calendar: "static/images/posters/calendar.webp",
		charts: "static/images/posters/charts.webp",
		clippedImage: "static/images/posters/crop.webp",
		clock: "static/images/posters/clock.webp",
		cloud: "static/images/posters/cloud.webp",
		color: "static/images/posters/color.webp",
		pill: "static/images/posters/cylinder.webp",
		contour: "static/images/posters/contour.webp",
		"Deco Shapes": "static/images/posters/shapes.webp",
		frame: "static/images/posters/frame.webp",
		flowerHeads: "static/images/posters/flowerHeads.webp",
		grid: "static/images/posters/grid.webp",
		layouts: "static/images/posters/layouts.webp",
		map: "static/images/posters/map.webp",
		polaroid: "static/images/posters/polaroid.webp",
		poppyFlower: "static/images/posters/poppyFlower.webp",
		spiral: "static/images/posters/spiral.webp",
		spotifyCard: "static/images/posters/spotify.webp",
		ribbon: "static/images/posters/ribbon.webp",
		stickerBadge: "static/images/posters/sticker-badge.webp",
		weather: "static/images/posters/weather.webp",
		waves: "static/images/posters/waves.webp",
	},
	presets: {
		calendar: "static/images/presets/calendar.webp",
		clippedImage: "static/images/presets/tornPaper.webp",
		clock: "static/images/presets/clock.webp",
		cylinder: "static/images/presets/cylinder.webp",
		polaroid: "static/images/presets/polaroid.webp",
		frame: "static/images/presets/frame.webp",
		map: "static/images/presets/map.webp",
		spotify: "static/images/presets/spotify.webp",
	},
};
